# Generated by Django 2.2.4 on 2019-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indobytes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
